/* Evidence-limited comparison. Nulls are unknown, never zero scores. */
window.TopicGap=(()=>{
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const weights=[40,35,25],names=['能力覆盖','流程集成','运行验证'];
 const calc=(a,b)=>{const matched=weights.map((w,i)=>a[i]!==null&&b[i]!==null?i:null).filter(i=>i!==null),coverage=matched.reduce((n,i)=>n+weights[i],0);const score=v=>coverage?matched.reduce((n,i)=>n+v[i]/5*weights[i],0)*100/coverage:null;return {matched,coverage,p:score(a),b:score(b),delta:coverage?score(a)-score(b):null}};
 const solo=a=>{const matched=weights.map((w,i)=>a[i]!==null?i:null).filter(i=>i!==null),coverage=matched.reduce((n,i)=>n+weights[i],0),score=coverage?matched.reduce((n,i)=>n+a[i]/5*weights[i],0)*100/coverage:null;return {coverage,score}};
 const range=a=>{const low=a.reduce((n,v,i)=>n+(v===null?0:v/5*weights[i]),0),missing=a.reduce((n,v,i)=>n+(v===null?weights[i]:0),0);return `${low.toFixed(1)}—${(low+missing).toFixed(1)}`};
 const number=n=>n===null?'待验证':n.toFixed(1);
 const radarPoint=(cx,cy,r,i,total,value)=>{if(value===null)return null;const angle=-Math.PI/2+i*2*Math.PI/total,rr=r*value/5;return [cx+Math.cos(angle)*rr,cy+Math.sin(angle)*rr]};
 const radar=(gaps,selected)=>{
  const w=780,h=520,cx=390,cy=252,r=174,total=gaps.length;
  const point=(i,v)=>radarPoint(cx,cy,r,i,total,v), outline=(values)=>values.map((v,i)=>point(i,v).join(',')).join(' ');
  const rings=[1,2,3,4,5].map(v=>`<polygon class="topic-gap-radar__ring" points="${outline(gaps.map(()=>v))}"/>`).join('');
  const productScores=gaps.map(item=>{const score=solo(item.product);return score.score===null?{coverage:0,score:40,estimated:true}:score}),baselineScores=gaps.map(item=>solo(item.baseline)),product=productScores.map(score=>score.score/20),baseline=baselineScores.map(score=>score.score===null?null:score.score/20);
  const axes=gaps.map((item,i)=>{const [x,y]=point(i,5),angle=-Math.PI/2+i*2*Math.PI/total,tx=cx+Math.cos(angle)*(r+27),ty=cy+Math.sin(angle)*(r+27),anchor=Math.cos(angle)>.25?'start':Math.cos(angle)<-.25?'end':'middle',productScore=productScores[i].estimated?'暂估 2/5（无公开评分数据，仅作图示补点）':`${number(productScores[i].score)} /100（覆盖 ${productScores[i].coverage}%）`,comparison=`产品 ${productScore}；B0 ${number(baselineScores[i].score)} /100（覆盖 ${baselineScores[i].coverage}%）`;return `<g class="topic-gap-radar__axis ${item.id===selected.id?'is-selected':''}" data-act="gap" data-id="${E(item.id)}" tabindex="0" role="button"><line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/><text x="${tx}" y="${ty+4}" text-anchor="${anchor}">${E(item.name)}</text><title>${E(item.name)} · ${comparison} · 覆盖率不同时请结合下方共同口径比较 · 点击查看明细</title></g>`}).join('');
  const dots=(values,cls)=>values.map((v,i)=>{if(v===null)return '';const [x,y]=point(i,v);return `<circle class="topic-gap-radar__dot ${cls}" cx="${x}" cy="${y}" r="${gaps[i].id===selected.id?4.8:3.8}"/>`}).join('');
  const series=(values,cls)=>{const known=values.map((value,i)=>value===null?null:point(i,value)).filter(Boolean),base=`topic-gap-radar__series topic-gap-radar__series--${cls}`;if(known.length===values.length)return `<polygon class="${base}" points="${known.map(p=>p.join(',')).join(' ')}"/>`;const fill=known.length>2?`<polygon class="${base} topic-gap-radar__series--partial" points="${known.map(p=>p.join(',')).join(' ')}"/>`:'';const segments=values.map((value,i)=>{const next=(i+1)%values.length;if(value===null||values[next]===null)return '';const [x1,y1]=point(i,value),[x2,y2]=point(next,values[next]);return `<line class="topic-gap-radar__segment topic-gap-radar__segment--${cls}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`}).join('');return fill+segments};
  return `<div class="topic-gap-radar"><div class="topic-gap-radar__head"><h3>能力差距雷达图</h3><div class="topic-gap-radar__legend"><span><i class="topic-gap-radar__swatch topic-gap-radar__swatch--product"></i>产品公开能力（含暂估点）</span><span><i class="topic-gap-radar__swatch topic-gap-radar__swatch--base"></i>B0 开源基线</span></div></div><svg class="topic-gap-radar__svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${E(gaps.length)} 项能力差距雷达图">${rings}${axes}${series(product,'product')}${series(baseline,'base')}${dots(product,'topic-gap-radar__dot--product')}${dots(baseline,'topic-gap-radar__dot--base')}</svg><p class="topic-gap-radar__note">无 MSS 专属公开评分的能力维度，图中按研究暂估 2/5 补点以闭合产品轮廓；详情仍标“待验证”。覆盖率不同的维度以下方共同口径分析为准。</p></div>`;
 };
 function render(c,{key,product,state,sourceList}){
  const cfg=window.PALANTIR_GAP_ASSESSMENT[key],audit=window.PALANTIR_GAP_DETAIL;
  const gaps=product.gaps.map(g=>({...g,...cfg.rows[g.id],...audit.rows[g.id]})),g=gaps.find(g=>g.id===state.gap)||gaps[0];state.gap=g.id;
  const v=calc(g.product,g.baseline),target=calc(g.target,g.baseline);
  const components=g.components.map(id=>audit.components[id]);
  const extra=key==='gotham'&&['G01','G03','G06','G08','G11'].includes(g.id)?['G-GC24']:key==='gotham'&&g.id==='G07'?['G-SEC-S1']:[];
  const table=`<div class="table-wrap"><table class="topic-data-table"><thead><tr><th>指标 / 权重</th><th>产品研究估分</th><th>B0 方案估分</th><th>目标要求</th><th>本项依据 / 缺口</th></tr></thead><tbody>${names.map((name,i)=>`<tr><td>${name}<br>${weights[i]}%</td><td>${g.product[i]===null?'待验证':g.product[i]+'/5 → '+(g.product[i]*weights[i]/5).toFixed(1)+' 分'}</td><td>${g.baseline[i]===null?'待验证':g.baseline[i]+'/5 → '+(g.baseline[i]*weights[i]/5).toFixed(1)+' 分'}</td><td>4/5</td><td>${E(i===0?g.rationale:i===1?(g.product[i]===null?'产品端缺具体跨模块配置与流程结果；基线只有拟议连接。':g.rationale+' 基线尚未实现组合流程。'):(g.product[i]===2?'产品端仅有限定实例运行披露；基线无测试。':'双方缺同环境、同数据、可复算结果，不计作零分。'))}</td></tr>`).join('')}</tbody></table></div>`;
  const formula=v.coverage?`共同可评分权重 W=${v.coverage}%。产品：(${v.matched.map(i=>`${g.product[i]}÷5×${weights[i]}`).join('＋')})÷${v.coverage}×100=${number(v.p)}；B0：(${v.matched.map(i=>`${g.baseline[i]}÷5×${weights[i]}`).join('＋')})÷${v.coverage}×100=${number(v.b)}；共同项差距=${number(v.p)}−${number(v.b)}=${number(v.delta)} 分。`:'没有双方共同可评分的指标，暂不计算分差。';
  c.innerHTML=`<div class="topic-gap-v2"><div class="topic-metrics"><div class="topic-metric"><strong>${gaps.length}</strong><small>逐项能力分析</small></div><div class="topic-metric"><strong>B0 方案基线</strong><small>固定候选版本 · 未搭建实测</small></div><div class="topic-metric"><strong>T1 需求基线</strong><small>建议验收条件 · 非客户既定要求</small></div></div>
  <details class="intel-gap-method" open><summary>评分依据、基线和计算规则</summary><p>产品侧按公开证据估分；B0 是本专题提出的开源组合方案，不是你的现有系统，也没有实测结果。分差表示在共同有依据的指标上的研究估计，不能当作性能领先幅度。</p><p><strong>完整分数 S = Σ（指标分 ÷ 5 × 权重）。</strong>权重合计 100%，40/35/25 是本专题的研究设定，不来自厂商，也未做统计校准。缺证据记为“待验证”；只有同口径测试确认不具备时才可记 0。</p><p><strong>部分资料计算：</strong>仅取双方都有分值的指标，参考分 = 已知加权贡献 ÷ 共同权重 × 100；同时显示共同可评分覆盖率。不同覆盖率的维度不能直接排名。可能总分区间将未知指标分别按 0 和 5 计算上下界，仅是数学边界，不是置信区间。</p><div class="intel-gap-method__grid">${names.map((n,i)=>`<article><strong>${n} · ${weights[i]}%</strong><p>${audit.rubrics[i].map(E).join('<br>')}</p></article>`).join('')}</div><p><strong>拟议环境：</strong>${E(audit.environment)}</p><p><strong>拟议连接：</strong>${E(audit.flow)}</p><p>证据状态分为：官方接口/服务说明、具名场景披露、公开代码和独立实测。前三者不能自动替代最后一项。本页“覆盖率”只统计可评分权重，不代表证据可信概率。</p></details>
  <div class="topic-gap-audit-layout"><aside class="topic-gap-audit-layout__side">${radar(gaps,g)}<div class="topic-card"><h3>能力维度与可比较范围</h3><div class="intel-gap-list">${gaps.map(item=>{const d=calc(item.product,item.baseline);return `<button data-act="gap" data-id="${E(item.id)}" aria-pressed="${g.id===item.id}"><strong>${E(item.name)}</strong><small>覆盖 ${d.coverage}% · ${d.delta===null?'待验证':'共同项差 '+number(d.delta)}</small></button>`}).join('')}</div><p class="topic-note">按研究维度排列，不再将缺证据项当作低能力项排序。</p></div></aside>
  <article class="intel-detail-panel"><span class="intel-kicker">${E(g.id)} · ${E(g.priority)}优先级</span><h3>${E(g.name)}</h3><div class="intel-gap-score-grid"><div class="intel-gap-score intel-gap-score--blue"><span>产品共同项参考分</span><strong>${number(v.p)}</strong></div><div class="intel-gap-score intel-gap-score--orange"><span>B0 共同项参考分</span><strong>${number(v.b)}</strong></div><div class="intel-gap-score intel-gap-score--red"><span>共同项差距 · 覆盖 ${v.coverage}%</span><strong>${number(v.delta)}</strong></div></div><p class="topic-note">以上为研究估分，未完成双方同条件测试。产品可能总分范围 ${range(g.product)}；B0 范围 ${range(g.baseline)}。范围重叠时不能据此宣称确定领先。</p>
  <h4>1. 产品依据与评分边界</h4><p>${E(g.rationale)}</p>${sourceList([...new Set([...g.sources,...extra])])}${table}<p class="topic-callout">${E(formula)}</p>
  <h4>2. 可复核的 B0 候选组件</h4><p>${E(g.baselineRationale)}</p><table class="topic-data-table"><thead><tr><th>固定版本</th><th>可以覆盖 / 仍需开发</th><th>版本核查</th></tr></thead><tbody>${components.map(x=>`<tr><td><a href="${E(x.url)}" target="_blank" rel="noopener noreferrer">${E(x.name)} ${E(x.version)}</a></td><td>${E(x.scope)}</td><td>${x.objectType==='tag'?'标签对象':'提交'}<br><code>${x.sha.slice(0,12)}</code><br>2026-09-30 核查</td></tr>`).join('')}</tbody></table><p class="topic-note">固定版本用于复核，不表示推荐上线版本或已验证互相兼容；依赖与许可证须在实施时按锁定版本核查。</p>
  <h4>3. T1 目标需求基线</h4><p>建议目标为三项均达到 4/5，即总分 80：明确场景验证能力、异常恢复可复现、独立实验通过。这是本专题建议值，尚未作为你的验收标准。</p><p><strong>本维度具体验收：</strong>${E(g.acceptance)}</p><p>在 B0 已评分的 ${target.coverage}% 权重内，目标参考分 ${number(target.p)} − B0 ${number(target.b)} = 待补 ${number(target.delta)} 分；运行验证等未知项另外列出，不能视为已经满足。</p>
  <h4>4. 同口径验证方案</h4><p>${E(g.test)}</p><p><strong>记录指标：</strong>${E(g.metric)}</p><p>验证双方时固定输入数据、用户数、权限矩阵与环境，并保存原始日志、版本清单和计算脚本；没有产品侧可访问环境时，只验证 B0，产品侧继续标记待验证。</p>
  <h4>5. 差距原因与实施顺序</h4><p>${E(g.open)}</p><p>${E(g.path)}</p><p class="topic-note">本轮完成材料与方法补充，没有运行产品对比实验。</p></article></div></div>`;
 }
 return {render,calculate:calc};
})();
