(() => {
'use strict';
const base=window.RESEARCH_DATA, lineage=window.PALANTIR_LINEAGE, dec=window.PALANTIR_DECONSTRUCTION;
const key=document.body.dataset.product||'home';
const oldLink=key==='home' && /^#(gotham|maven)\/(products|technology|gaps|restoration)$/.exec(location.hash||'');
if(oldLink){location.replace(`${oldLink[1]}.html?tab=${oldLink[2]}`);return}
const sources={...base.sources,...lineage.extraSources};
const tabs=[['products','产品谱系'],['technology','技术谱系'],['gaps','差距分析'],['restoration','技术破解']];
const techTabs=[['graph','可视化技术 / 事件图谱'],['routes','关键技术路线演化']];
const restTabs=[['scenarios','场景实验'],['principle','四层原理网图'],['opensource','开源项目索引'],['parameters','逐项目验证参数包']];
const query=new URLSearchParams(location.search);
const state={tab:tabs.some(x=>x[0]===query.get('tab'))?query.get('tab'):'products',sub:query.get('sub')||'',search:'',group:'全部',status:'全部',graphSearch:'',graphRelations:true,route:'all',routeNode:'',routeRelations:true,gap:'',node:'',project:'',category:'全部',drawer:null};
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const a=(arr)=>Array.isArray(arr)?arr:[];
const $=(sel)=>document.querySelector(sel);
const product=base[key], graph=lineage[key], deconstruction=dec[key];
function sourceList(ids){return `<div class="topic-source-list">${a(ids).map(id=>{const s=sources[id];return s?`<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer" title="${e(s.title)}">${e(id)} · ${e(s.type)}</a>`:`<span>${e(id)}（待核）</span>`}).join('')}</div>`}
function field(label,value){return `<dl class="topic-field"><dt>${e(label)}</dt><dd>${value}</dd></dl>`}
function shell(){
 const nav=(k,name)=>`<li><a class="navigation__item topic-link" href="${k}.html" ${key===k?'aria-current="page"':''}>${name}</a></li>`;
 $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><svg class="brand__mark" viewBox="0 0 88 88" aria-hidden="true"><image href="./assets/brand-logo.png" x="-166" y="-8" width="265" height="152"/></svg><div class="brand__text"><p class="brand__name">数智系统</p><p class="brand__product">Palantir 专题研究</p></div></div><nav class="navigation" aria-label="专题导航"><div class="navigation__group"><p class="navigation__title">专题入口</p><ul class="navigation__list">${nav('index','专题总览')}${nav('gotham','Gotham 产品专题')}${nav('maven','Maven MSS 产品专题')}</ul></div><div class="navigation__group"><p class="navigation__title">研究维度</p><ul class="navigation__list">${key==='home'?'<li class="navigation__item">选择产品进入四维研究</li>':tabs.map(([id,label])=>`<li><button class="navigation__item" data-act="tab" data-id="${id}" ${state.tab===id?'aria-current="page"':''}>${label}</button></li>`).join('')}</ul></div></nav></aside><div class="shell-body"><header class="topbar"><p class="topbar__project">情报服务平台 · Palantir 专题</p><p class="topbar__level">公开资料研究</p><p class="topbar__object">${key==='home'?'Gotham / Maven Smart System':e(product.fullName)}</p></header><main class="workspace" id="main"></main></div></div><div id="overlay"></div>`;
}
function renderHome(){const cards=['gotham','maven'].map(k=>{const p=base[k],g=lineage[k];return `<article class="topic-hero"><div class="topic-kicker">产品专题 / ${k==='gotham'?'01':'02'}</div><h2>${e(p.fullName)}</h2><p>${e(p.thesis)}</p><div class="topic-chain">${p.chain.map(x=>`<span>${e(x)}</span>`).join('')}</div><div class="topic-metrics"><div class="topic-metric"><strong>${p.products.length}</strong><small>谱系对象</small></div><div class="topic-metric"><strong>${g.events.length}</strong><small>公开事件 / 证据节点</small></div></div><a class="topic-button topic-button--primary" href="${k}.html">进入${e(p.name)}专题 →</a></article>`}).join('');$('#main').innerHTML=`<section class="page-header"><div><p class="topic-kicker">PALANTIR RESEARCH ATLAS</p><h1>Gotham 与 Maven MSS 专题研究</h1><p class="page-header__description">沿用离线情报服务平台的导航、数据表、分层图谱和原理网图方式组织材料。</p></div></section><div class="topic-home-help">研究范围：产品谱系、技术谱系、差距分析、技术破解。公开事件、厂商主张、工程候选和未知项分别标注；技术破解展示可隔离验证的候选方案。</div><div class="topic-grid" style="margin-top:15px">${cards}</div><p class="topic-note" style="margin-top:15px">内容来自四份调研材料与可追溯公开来源。两份综合报告已纳入结构和边界梳理。</p>`}
function header(){return `<div class="topic-header"><div><div class="topic-kicker">PALANTIR / ${e(product.name.toUpperCase())}</div><h1>${e(product.fullName)} · 四维研究</h1><p class="topic-lead">${e(product.thesis)}</p></div><a class="topic-button" href="index.html">返回专题总览</a></div><div class="topic-boundary"><strong>研究边界：</strong>${e(product.boundary)}</div><div class="topic-metrics"><div class="topic-metric"><strong>${product.products.length}</strong><small>产品 / 能力对象</small></div><div class="topic-metric"><strong>${graph.events.length}</strong><small>公开事件与资料截面</small></div><div class="topic-metric"><strong>${product.gaps.length}</strong><small>差距项</small></div><div class="topic-metric"><strong>${deconstruction.projects.length}</strong><small>开源验证参照</small></div></div><div class="tabs-viewport topic-tabs"><div class="tabs" role="tablist">${tabs.map(([id,label])=>`<button class="tab" role="tab" data-act="tab" data-id="${id}" aria-selected="${state.tab===id}">${label}</button>`).join('')}</div></div>`}
function render(){shell();if(key==='home'){renderHome();return}const main=$('#main');main.innerHTML=header()+`<div id="content" class="tab-panel"></div>`;renderContent()}
function renderContent(){const c=$('#content');if(!c)return;switch(state.tab){case'products':renderProducts(c);break;case'technology':renderTechnology(c);break;case'gaps':window.TopicGap.render(c,{key,product,state,sourceList});break;case'restoration':renderRestoration(c);break}}
function go(tab,sub){state.tab=tab;state.sub=sub||'';state.drawer=null;const q=new URLSearchParams();q.set('tab',tab);if(sub)q.set('sub',sub);try{history.replaceState(null,'',`${location.pathname}?${q}`)}catch{}render()}
function renderProducts(c){const groups=[...new Set(product.products.map(p=>p.group))],statuses=[...new Set(product.products.map(p=>p.status))];c.innerHTML=`<div class="pc-root"><div class="pc-context"><div class="pc-context__item"><span class="pc-context__label">研究对象</span><strong class="pc-context__value">${e(product.fullName)}</strong></div><div class="pc-context__item"><span class="pc-context__label">产品谱系范围</span><strong class="pc-context__value">${groups.length} 组 / ${product.products.length} 项</strong></div><div class="pc-context__item"><span class="pc-context__label">判定规则</span><strong class="pc-context__value">区分原生产品、关联平台、公开能力与实例</strong></div></div><div class="pc-toolbar"><label class="pc-control pc-control--search"><span class="pc-control__label">名称 / 描述检索</span><input class="pc-control__input" id="product-search" value="${e(state.search)}" placeholder="搜索产品、能力或证据"></label><label class="pc-control"><span class="pc-control__label">谱系分组</span><select class="pc-control__select" id="product-group"><option>全部</option>${groups.map(x=>`<option ${state.group===x?'selected':''}>${e(x)}</option>`).join('')}</select></label><label class="pc-control"><span class="pc-control__label">证据状态</span><select class="pc-control__select" id="product-status"><option>全部</option>${statuses.map(x=>`<option ${state.status===x?'selected':''}>${e(x)}</option>`).join('')}</select></label></div><div class="pc-results"><div id="product-table"></div></div></div>`;renderProductTable()}
function renderProductTable(){const rows=product.products.filter(p=>(state.group==='全部'||p.group===state.group)&&(state.status==='全部'||p.status===state.status)&&(`${p.name} ${p.summary} ${p.kind}`.toLowerCase().includes(state.search.toLowerCase())));const groups=[...new Set(rows.map(p=>p.group))];$('#product-table').innerHTML=rows.length?`<div class="pc-table-wrap"><table class="pc-table"><thead><tr><th>谱系分组</th><th>对象类型</th><th>名称</th><th>公开描述</th><th>证据状态</th><th>来源</th><th>详情</th></tr></thead><tbody>${groups.map(g=>`<tr class="pc-table__group-row"><td colspan="7">${e(g)}<span class="pc-table__group-count">${rows.filter(x=>x.group===g).length} 项</span></td></tr>${rows.filter(p=>p.group===g).map(p=>`<tr class="pc-table__row"><td>${e(p.group)}</td><td><span class="pc-object-type">${e(p.kind)}</span></td><td><button class="pc-table__name" data-act="product" data-id="${e(p.id)}">${e(p.name)}</button></td><td>${e(p.summary)}</td><td><span class="topic-status">${e(p.status)}</span></td><td>${sourceList(p.sources)}</td><td><button class="topic-button" data-act="product" data-id="${e(p.id)}">查看</button></td></tr>`).join('')}`).join('')}</tbody></table></div>`:`<div class="topic-empty">没有匹配项。请调整关键词或筛选条件。</div>`}
function renderTechnology(c){const sub=techTabs.some(x=>x[0]===state.sub)?state.sub:'graph';state.sub=sub;c.innerHTML=`<div class="topic-subtabs" role="tablist">${techTabs.map(([id,label])=>`<button class="topic-subtab" role="tab" aria-selected="${sub===id}" data-act="tech-sub" data-id="${id}">${label}</button>`).join('')}</div><div id="tech-body"></div>`;if(sub==='graph')window.TopicTechnology.renderGraph($('#tech-body'),{key,product,graph,state});else window.TopicTechnology.renderRoutes($('#tech-body'),{key,product,graph,state,sources,sourceList,field})}
function renderRestoration(c){const sub=restTabs.some(x=>x[0]===state.sub)?state.sub:'scenarios';state.sub=sub;c.innerHTML=`<div class="topic-subtabs" role="tablist">${restTabs.map(([id,label])=>`<button class="topic-subtab" role="tab" aria-selected="${sub===id}" data-act="rest-sub" data-id="${id}">${label}</button>`).join('')}</div><div id="rest-body"></div>`;const body=$('#rest-body');if(sub==='scenarios')renderScenarios(body);else if(sub==='principle')renderPrinciple(body);else if(sub==='opensource')renderOpenSource(body);else renderParameters(body)}
function renderScenarios(c){c.innerHTML=`<div class="topic-graph-note">场景使用合成数据或公开历史数据，以隔离实验验证机制；项目、阈值和流转规则均非闭源产品内部实现。</div><div class="topic-grid" style="margin-top:12px">${product.scenarios.map((s,i)=>`<article class="topic-card"><div class="topic-kicker">SCENARIO ${String(i+1).padStart(2,'0')}</div><h3>${e(s.name)}</h3><div class="topic-scenario-flow">${s.flow.map(x=>`<span>${e(x)}</span>`).join('')}</div><p><strong>验证指标：</strong>${e(s.measure)}</p><p><strong>工程参照：</strong>${e(s.reference)}</p><button class="topic-button" data-act="scenario" data-id="${e(s.id)}">查看实验卡与证据</button></article>`).join('')}</div>`}
function renderPrinciple(c){const nodes=deconstruction.nodes.map(([id,name,level,status,src])=>({id,name,level,status,src}));const levels=['目标能力','关键原理','功能模块','实现单元'];const selected=nodes.find(n=>n.id===state.node)||nodes[0];state.node=selected.id;const incoming=deconstruction.edges.filter(x=>x.to.includes(selected.id)).map(x=>x.from),outgoing=deconstruction.edges.filter(x=>x.from===selected.id).flatMap(x=>x.to);const related=[...new Set([...incoming,...outgoing])];c.innerHTML=`<div class="topic-graph-note">四层结构对照参考版“目标能力 → 关键原理 → 功能模块 → 实现单元”。线条中实线表示公开机制支撑，虚线表示工程候选映射；不能解读为 Palantir 内部架构。</div><div class="topic-principle" style="margin-top:12px"><div class="topic-principle-canvas"><svg class="topic-principle-svg" id="principle-svg" aria-hidden="true"></svg><div class="topic-principle-columns">${levels.map((l,i)=>`<div class="topic-principle-col"><h3>0${i+1} ${l}</h3>${nodes.filter(n=>n.level===i).map(n=>`<button class="topic-principle-node" id="node-${e(n.id)}" data-act="node" data-id="${e(n.id)}" aria-pressed="${n.id===selected.id}"><strong>${e(n.name)}</strong><small>${e(n.id)} · ${e(n.status)}</small></button>`).join('')}</div>`).join('')}</div></div><aside class="topic-card topic-sticky"><div class="topic-kicker">原理节点 / ${e(selected.id)}</div><h3>${e(selected.name)}</h3>${field('层级',e(levels[selected.level]))}${field('证据性质',e(selected.status))}${field('关联节点',related.length?related.map(id=>{const n=nodes.find(x=>x.id===id);return `<button class="topic-button" data-act="node" data-id="${e(id)}" style="margin:3px">${e(n?.name||id)}</button>`}).join(''):'暂无')}${field('开源参照',deconstruction.projects.filter(p=>p.node===selected.id).map(p=>`<button class="topic-button" data-act="project" data-id="${e(p.id)}" style="margin:3px">${e(p.name)}</button>`).join('')||'待补充')}<h3>来源</h3>${sourceList(selected.src)}</aside></div>`;requestAnimationFrame(drawPrincipleEdges)}
function drawPrincipleEdges(){const svg=$('#principle-svg'),canvas=$('.topic-principle-canvas');if(!svg||!canvas)return;const bounds=canvas.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${Math.max(canvas.scrollWidth,760)} ${canvas.scrollHeight}`);svg.setAttribute('width',Math.max(canvas.scrollWidth,760));svg.setAttribute('height',canvas.scrollHeight);const lines=[];for(const edge of deconstruction.edges){const fr=$(`#node-${edge.from}`)?.getBoundingClientRect();if(!fr)continue;for(const id of edge.to){const to=$(`#node-${id}`)?.getBoundingClientRect();if(!to)continue;const x1=fr.right-bounds.left,y1=fr.top-bounds.top+fr.height/2,x2=to.left-bounds.left,y2=to.top-bounds.top+to.height/2;const active=state.node===edge.from||state.node===id;lines.push(`<path d="M ${x1} ${y1} C ${x1+24} ${y1}, ${x2-24} ${y2}, ${x2} ${y2}" fill="none" stroke="${active?'#1f68b0':'#a8bfd5'}" stroke-width="${active?2.5:1.4}" ${edge.type==='observed'?'':'stroke-dasharray="5 4"'} opacity="${active?1:.7}"/>`)}}svg.innerHTML=lines.join('')}
function renderOpenSource(c){const projects=deconstruction.projects,cats=['全部',...new Set(projects.map(x=>x.category))],rows=projects.filter(p=>state.category==='全部'||p.category===state.category);c.innerHTML=`<div class="topic-graph-note">开源仓库用于检验相似工程机制，不构成 Palantir 技术栈归因。目录和许可证为研究参照，实际使用前仍需核对仓库版本。</div><div class="topic-card" style="margin-top:12px"><div class="topic-project-filter">${cats.map(x=>`<button data-act="category" data-id="${e(x)}" aria-pressed="${state.category===x}">${e(x)}</button>`).join('')}</div><div class="table-wrap"><table class="topic-data-table"><thead><tr><th>类别 / 项目</th><th>语言 / 许可证</th><th>映射原理</th><th>代码入口</th><th>验证</th></tr></thead><tbody>${rows.map(p=>{const node=deconstruction.nodes.find(x=>x[0]===p.node);return `<tr><td><strong>${e(p.name)}</strong><br><small>${e(p.category)}</small></td><td>${e(p.language)}<br><small>${e(p.license)}</small></td><td>${e(node?.[1]||p.node)}</td><td><code>${e(p.files)}</code></td><td><button class="topic-button" data-act="project" data-id="${e(p.id)}">参数包 →</button></td></tr>`}).join('')}</tbody></table></div></div>`}
function renderParameters(c){const projects=deconstruction.projects,sel=projects.find(x=>x.id===state.project)||projects[0];state.project=sel.id;const params=deconstruction.parameters,groups=[...new Set(params.map(x=>x[4]))];c.innerHTML=`<div class="topic-graph-note">这是面向开源候选的隔离验证参数包。数值为实验输入范围或待计算指标，不是 Gotham/MSS 的真实性能。</div><div class="topic-parameter-grid" style="margin-top:12px"><div class="topic-project-list">${projects.map(p=>`<button data-act="select-project" data-id="${e(p.id)}" aria-pressed="${sel.id===p.id}"><strong>${e(p.name)}</strong><small>${e(p.id)} · ${e(p.category)}</small></button>`).join('')}</div><div class="topic-card"><div class="topic-kicker">PROJECT VALIDATION PACK / ${e(sel.id)}</div><h3>${e(sel.name)}</h3>${field('类别 / 语言 / 许可证',`${e(sel.category)} · ${e(sel.language)} · ${e(sel.license)}`)}${field('原理映射',e(deconstruction.nodes.find(x=>x[0]===sel.node)?.[1]||sel.node))}${field('代码查看入口',`<code>${e(sel.files)}</code>`)}${field('概念数据流',`<div class="topic-mini-flow">${e(sel.flow)}</div>`)}${field('能力边界',e(sel.limits))}<p><a href="${e(sel.url)}" target="_blank" rel="noopener noreferrer">打开项目官方仓库 / 主页 ↗</a></p><button class="topic-button" data-act="export" data-id="${e(sel.id)}">导出本项目验证包 JSON</button><h3>隔离实验参数与验收指标</h3><div class="table-wrap"><table class="topic-data-table"><thead><tr><th>组别</th><th>编号</th><th>字段</th><th>性质</th><th>设定 / 计算口径</th></tr></thead><tbody>${groups.map(g=>params.filter(x=>x[4]===g).map(x=>`<tr><td>${e(g)}</td><td>${e(x[0])}</td><td>${e(x[1])}</td><td>${e(x[2])}</td><td>${e(x[3])}</td></tr>`).join('')).join('')}</tbody></table></div></div></div>`}
function drawer(title,kicker,body){$('#overlay').innerHTML=`<div class="topic-drawer-backdrop" data-act="close"></div><aside class="topic-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div class="topic-drawer__head"><div><div class="topic-kicker" style="color:#a7c5e5">${e(kicker)}</div><h2 id="drawer-title">${e(title)}</h2></div><button class="topic-drawer__close" data-act="close" aria-label="关闭详情">✕</button></div><div class="topic-drawer__body">${body}</div></aside>`;$('.topic-drawer__close')?.focus()}
function closeDrawer(){$('#overlay').innerHTML=''}
function openProduct(id){const p=product.products.find(x=>x.id===id);if(!p)return;const related=graph.events.filter(ev=>ev.object===p.id);drawer(p.name,`${p.group} / ${p.kind}`,`${field('产品定位',e(p.summary))}${field('证据状态',`<span class="topic-status">${e(p.status)}</span>`)}${field('尚不明确',e(p.unknown))}<h3>产品关系与公开节点</h3>${related.length?related.map(ev=>`<button class="topic-button" data-act="event" data-id="${e(ev.id)}" style="margin:4px">${e(ev.date)} · ${e(ev.title)}</button>`).join(''):'暂无对应的独立事件节点；请以现有来源为准。'}<h3>可追溯资料</h3>${sourceList(p.sources)}<h3>继续阅读</h3><button class="topic-button" data-act="tab" data-id="technology">查看技术谱系</button>`)}
function openEvent(id){const ev=graph.events.find(x=>x.id===id);if(!ev)return;const ob=graph.objects.find(x=>x.id===ev.object),p=product.products.find(x=>x.id===ev.object);drawer(ev.title,`${ev.id} / ${ev.kind}`,`${field('时间 / 资料截面',e(ev.date))}${field('对应对象',e(ob?.name||ev.object))}${field('公开事实与边界',e(ev.note))}${p?field('产品目录',`<button class="topic-button" data-act="product" data-id="${e(p.id)}">${e(p.name)} →</button>`):''}<h3>公开来源</h3>${sourceList(ev.sources)}`)}
function openObject(id){const ob=graph.objects.find(x=>x.id===id);if(!ob)return;const p=product.products.find(x=>x.id===id),events=graph.events.filter(x=>x.object===id),relations=graph.relations.filter(x=>x.from===id||x.to===id);drawer(ob.name,'技术谱系 / 能力对象',`${field('所属层级',e(graph.layers.find(x=>x.id===ob.layer)?.label))}${p?field('产品目录摘要',e(p.summary)):''}${p?field('不确定边界',e(p.unknown)):''}<h3>公开事件</h3>${events.length?events.map(ev=>`<button class="topic-button" data-act="event" data-id="${e(ev.id)}" style="margin:4px">${e(ev.date)} · ${e(ev.title)}</button>`).join(''):'暂无单独事件节点'}<h3>对象关系</h3>${relations.map(r=>`<p>${e(graph.objects.find(x=>x.id===r.from)?.name||r.from)} → ${e(graph.objects.find(x=>x.id===r.to)?.name||r.to)}：${e(r.label)}</p>`).join('')}${p?`<h3>来源</h3>${sourceList(p.sources)}`:''}`)}
function openScenario(id){const s=product.scenarios.find(x=>x.id===id);if(!s)return;drawer(s.name,`${id} / 隔离验证场景`,`${field('实验流程',`<div class="topic-scenario-flow">${s.flow.map(x=>`<span>${e(x)}</span>`).join('')}</div>`)}${field('验证指标',e(s.measure))}${field('开源 / 工程参照',e(s.reference))}${field('解释边界',e(s.boundary))}<h3>公开依据</h3>${sourceList(s.sources)}<h3>进一步拆解</h3><button class="topic-button" data-act="rest-sub" data-id="principle">进入四层原理网图 →</button>`)}
function exportPack(id){const p=deconstruction.projects.find(x=>x.id===id);if(!p)return;const output={researchProduct:product.fullName,candidateProject:p,principleNode:deconstruction.nodes.find(n=>n[0]===p.node),parameters:deconstruction.parameters.map(([id,name,kind,value,group])=>({id,name,kind,value,group})),disclaimer:'隔离验证设计；不是 Palantir 内部实现或真实性能。'};const blob=new Blob([JSON.stringify(output,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${key}-${p.id}-validation-pack.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
document.addEventListener('click',ev=>{const t=ev.target.closest('[data-act]');if(!t)return;const act=t.dataset.act,id=t.dataset.id;if(act==='tab')go(id);else if(act==='tech-sub')go('technology',id);else if(act==='rest-sub')go('restoration',id);else if(act==='close')closeDrawer();else if(act==='product')openProduct(id);else if(act==='event')openEvent(id);else if(act==='object')openObject(id);else if(act==='scenario')openScenario(id);else if(act==='route-focus'){state.route=id;window.TopicTechnology.renderRoutes($('#tech-body'),{key,product,graph,state,sources,sourceList,field})}else if(act==='route-node'){state.routeNode=id;window.TopicTechnology.renderRoutes($('#tech-body'),{key,product,graph,state,sources,sourceList,field})}else if(act==='route-relations'){state.routeRelations=!state.routeRelations;window.TopicTechnology.renderRoutes($('#tech-body'),{key,product,graph,state,sources,sourceList,field})}else if(act==='graph-relations'){state.graphRelations=!state.graphRelations;window.TopicTechnology.renderGraph($('#tech-body'),{key,product,graph,state})}else if(act==='gap'){state.gap=id;window.TopicGap.render($('#content'),{key,product,state,sourceList})}else if(act==='node'){state.node=id;renderPrinciple($('#rest-body'))}else if(act==='category'){state.category=id;renderOpenSource($('#rest-body'))}else if(act==='project'){closeDrawer();state.project=id;go('restoration','parameters')}else if(act==='select-project'){state.project=id;renderParameters($('#rest-body'))}else if(act==='export')exportPack(id)});
document.addEventListener('input',ev=>{if(ev.target.id==='product-search'){state.search=ev.target.value;renderProductTable()}else if(ev.target.id==='graph-search'){state.graphSearch=ev.target.value;const term=state.graphSearch.toLowerCase();document.querySelectorAll('.fsg-object-node').forEach(n=>n.classList.toggle('is-highlighted',!!term&&n.getAttribute('aria-label').toLowerCase().includes(term)));document.querySelectorAll('.fsg-event').forEach(n=>n.classList.toggle('is-highlighted',!!term&&n.getAttribute('aria-label').toLowerCase().includes(term)))}});
document.addEventListener('change',ev=>{if(ev.target.id==='product-group'){state.group=ev.target.value;renderProductTable()}else if(ev.target.id==='product-status'){state.status=ev.target.value;renderProductTable()}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape')closeDrawer();if((ev.key==='Enter'||ev.key===' ')&&ev.target.matches('svg [data-act]')){ev.preventDefault();ev.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
window.addEventListener('resize',()=>{if(state.tab==='restoration'&&state.sub==='principle')drawPrincipleEdges()});
render();
})();
